export interface DictEntry {
  word: string;
  phonetic: string;
  definition: string;
  example: string;
}

const DICT: Record<string, DictEntry> = {
  i: { word: 'I', phonetic: '/aɪ/', definition: 'pron. 我', example: 'I am a student.' },
  you: { word: 'you', phonetic: '/juː/', definition: 'pron. 你；你们', example: 'You are welcome.' },
  he: { word: 'he', phonetic: '/hiː/', definition: 'pron. 他', example: 'He is my brother.' },
  she: { word: 'she', phonetic: '/ʃiː/', definition: 'pron. 她', example: 'She is a doctor.' },
  it: { word: 'it', phonetic: '/ɪt/', definition: 'pron. 它', example: 'It is raining.' },
  we: { word: 'we', phonetic: '/wiː/', definition: 'pron. 我们', example: 'We are friends.' },
  they: { word: 'they', phonetic: '/ðeɪ/', definition: 'pron. 他们；她们；它们', example: 'They are coming.' },
  me: { word: 'me', phonetic: '/miː/', definition: 'pron. 我（宾格）', example: 'Give it to me.' },
  him: { word: 'him', phonetic: '/hɪm/', definition: 'pron. 他（宾格）', example: 'I saw him yesterday.' },
  her: { word: 'her', phonetic: '/hɜːr/', definition: 'pron. 她（宾格）；她的', example: 'I love her.' },
  us: { word: 'us', phonetic: '/ʌs/', definition: 'pron. 我们（宾格）', example: 'Join us!' },
  them: { word: 'them', phonetic: '/ðem/', definition: 'pron. 他们（宾格）', example: 'I know them.' },
  my: { word: 'my', phonetic: '/maɪ/', definition: 'pron. 我的', example: 'This is my book.' },
  your: { word: 'your', phonetic: '/jɔːr/', definition: 'pron. 你的；你们的', example: 'What is your name?' },
  his: { word: 'his', phonetic: '/hɪz/', definition: 'pron. 他的', example: 'That is his car.' },
  its: { word: 'its', phonetic: '/ɪts/', definition: 'pron. 它的', example: 'The dog wagged its tail.' },
  our: { word: 'our', phonetic: '/ˈaʊər/', definition: 'pron. 我们的', example: 'Our team won.' },
  their: { word: 'their', phonetic: '/ðer/', definition: 'pron. 他们的', example: 'Their house is big.' },
  this: { word: 'this', phonetic: '/ðɪs/', definition: 'pron./det. 这，这个', example: 'This is delicious.' },
  that: { word: 'that', phonetic: '/ðæt/', definition: 'pron./det. 那，那个；conj. 以至于', example: 'That is true.' },
  these: { word: 'these', phonetic: '/ðiːz/', definition: 'pron./det. 这些', example: 'These are mine.' },
  those: { word: 'those', phonetic: '/ðoʊz/', definition: 'pron./det. 那些', example: 'Those are expensive.' },
  one: { word: 'one', phonetic: '/wʌn/', definition: 'num. 一；pron. 一个人', example: 'One plus one is two.' },
  all: { word: 'all', phonetic: '/ɔːl/', definition: 'det./pron. 全部，所有', example: 'All of us agree.' },
  some: { word: 'some', phonetic: '/sʌm/', definition: 'det./pron. 一些', example: 'I need some water.' },
  any: { word: 'any', phonetic: '/ˈeni/', definition: 'det./pron. 任何；一些', example: 'Do you have any questions?' },
  each: { word: 'each', phonetic: '/iːtʃ/', definition: 'det./pron. 每个', example: 'Each student has a book.' },
  every: { word: 'every', phonetic: '/ˈevri/', definition: 'det. 每个', example: 'Every day is a new day.' },
  another: { word: 'another', phonetic: '/əˈnʌðər/', definition: 'det./pron. 另一个', example: 'Can I have another?' },
  other: { word: 'other', phonetic: '/ˈʌðər/', definition: 'adj./pron. 其他的', example: 'The other day I saw him.' },
  such: { word: 'such', phonetic: '/sʌtʃ/', definition: 'det./pron. 这样的；如此', example: 'Such is life.' },
  what: { word: 'what', phonetic: '/wʌt/', definition: 'pron./det. 什么', example: 'What do you want?' },
  which: { word: 'which', phonetic: '/wɪtʃ/', definition: 'pron./det. 哪一个', example: 'Which one do you prefer?' },
  who: { word: 'who', phonetic: '/huː/', definition: 'pron. 谁', example: 'Who is he?' },
  whom: { word: 'whom', phonetic: '/huːm/', definition: 'pron. 谁（宾格）', example: 'To whom did you speak?' },
  whose: { word: 'whose', phonetic: '/huːz/', definition: 'pron./det. 谁的', example: 'Whose book is this?' },
  myself: { word: 'myself', phonetic: '/maɪˈself/', definition: 'pron. 我自己', example: 'I did it myself.' },
  yourself: { word: 'yourself', phonetic: '/jɔːrˈself/', definition: 'pron. 你自己', example: 'Help yourself.' },
  himself: { word: 'himself', phonetic: '/hɪmˈself/', definition: 'pron. 他自己', example: 'He did it himself.' },
  herself: { word: 'herself', phonetic: '/hɜːrˈself/', definition: 'pron. 她自己', example: 'She bought it herself.' },
  itself: { word: 'itself', phonetic: '/ɪtˈself/', definition: 'pron. 它自己', example: 'The door opened by itself.' },
  ourselves: { word: 'ourselves', phonetic: '/ˌaʊərˈselvz/', definition: 'pron. 我们自己', example: 'We enjoyed ourselves.' },
  themselves: { word: 'themselves', phonetic: '/ðemˈselvz/', definition: 'pron. 他们自己', example: 'They did it themselves.' },
  am: { word: 'am', phonetic: '/æm/', definition: 'v. 是（第一人称单数）', example: 'I am happy.' },
  is: { word: 'is', phonetic: '/ɪz/', definition: 'v. 是（第三人称单数）', example: 'She is kind.' },
  are: { word: 'are', phonetic: '/ɑːr/', definition: 'v. 是（复数/第二人称）', example: 'You are right.' },
  was: { word: 'was', phonetic: '/wʌz/', definition: 'v. 是（am/is 的过去式）', example: 'He was late.' },
  were: { word: 'were', phonetic: '/wɜːr/', definition: 'v. 是（are 的过去式）', example: 'They were tired.' },
  be: { word: 'be', phonetic: '/biː/', definition: 'v. 是；存在', example: 'To be or not to be.' },
  been: { word: 'been', phonetic: '/bɪn/', definition: 'v. be 的过去分词', example: 'I have been there.' },
  being: { word: 'being', phonetic: '/ˈbiːɪŋ/', definition: 'n. 存在；生物 / v. be 的现在分词', example: 'A human being.' },
  have: { word: 'have', phonetic: '/hæv/', definition: 'v. 有；吃；进行', example: 'I have a car.' },
  has: { word: 'has', phonetic: '/hæz/', definition: 'v. have 的第三人称单数', example: 'She has a cat.' },
  had: { word: 'had', phonetic: '/hæd/', definition: 'v. have 的过去式/过去分词', example: 'I had breakfast.' },
  having: { word: 'having', phonetic: '/ˈhævɪŋ/', definition: 'v. have 的现在分词', example: 'I am having fun.' },
  do: { word: 'do', phonetic: '/duː/', definition: 'v. 做；助动词', example: 'What do you do?' },
  does: { word: 'does', phonetic: '/dʌz/', definition: 'v. do 的第三人称单数', example: 'She does her homework.' },
  did: { word: 'did', phonetic: '/dɪd/', definition: 'v. do 的过去式', example: 'I did my best.' },
  doing: { word: 'doing', phonetic: '/ˈduːɪŋ/', definition: 'v. do 的现在分词 / n. 行为', example: 'How are you doing?' },
  done: { word: 'done', phonetic: '/dʌn/', definition: 'v. do 的过去分词 / adj. 完成的', example: 'I am done.' },
  will: { word: 'will', phonetic: '/wɪl/', definition: 'modal v. 将；愿意 / n. 意志', example: 'I will help you.' },
  would: { word: 'would', phonetic: '/wʊd/', definition: 'modal v. will 的过去式；愿意', example: 'Would you like tea?' },
  shall: { word: 'shall', phonetic: '/ʃæl/', definition: 'modal v. 将要；应该', example: 'Shall we go?' },
  should: { word: 'should', phonetic: '/ʃʊd/', definition: 'modal v. 应该', example: 'You should study.' },
  may: { word: 'may', phonetic: '/meɪ/', definition: 'modal v. 可能；可以', example: 'You may leave now.' },
  might: { word: 'might', phonetic: '/maɪt/', definition: 'modal v. may 的过去式；可能', example: 'It might rain.' },
  can: { word: 'can', phonetic: '/kæn/', definition: 'modal v. 能；可以 / n. 罐头', example: 'I can swim.' },
  could: { word: 'could', phonetic: '/kʊd/', definition: 'modal v. can 的过去式；能够', example: 'Could you help me?' },
  must: { word: 'must', phonetic: '/mʌst/', definition: 'modal v. 必须', example: 'You must try harder.' },
  say: { word: 'say', phonetic: '/seɪ/', definition: 'v. 说', example: 'What did you say?' },
  said: { word: 'said', phonetic: '/sed/', definition: 'v. say 的过去式/过去分词', example: 'He said hello.' },
  says: { word: 'says', phonetic: '/sez/', definition: 'v. say 的第三人称单数', example: 'She says yes.' },
  go: { word: 'go', phonetic: '/ɡoʊ/', definition: 'v. 去；走', example: 'Let us go!' },
  goes: { word: 'goes', phonetic: '/ɡoʊz/', definition: 'v. go 的第三人称单数', example: 'She goes to school.' },
  went: { word: 'went', phonetic: '/went/', definition: 'v. go 的过去式', example: 'I went home.' },
  gone: { word: 'gone', phonetic: '/ɡɔːn/', definition: 'v. go 的过去分词 / adj. 离开的', example: 'He is gone.' },
  going: { word: 'going', phonetic: '/ˈɡoʊɪŋ/', definition: 'v. go 的现在分词 / n. 离去', example: 'I am going out.' },
  get: { word: 'get', phonetic: '/ɡet/', definition: 'v. 得到；变得', example: 'I get it.' },
  gets: { word: 'gets', phonetic: '/ɡets/', definition: 'v. get 的第三人称单数', example: 'He gets angry.' },
  got: { word: 'got', phonetic: '/ɡɑːt/', definition: 'v. get 的过去式/过去分词', example: 'I got a gift.' },
  getting: { word: 'getting', phonetic: '/ˈɡetɪŋ/', definition: 'v. get 的现在分词', example: 'I am getting tired.' },
  make: { word: 'make', phonetic: '/meɪk/', definition: 'v. 制作；使', example: 'Make yourself at home.' },
  makes: { word: 'makes', phonetic: '/meɪks/', definition: 'v. make 的第三人称单数', example: 'She makes cakes.' },
  made: { word: 'made', phonetic: '/meɪd/', definition: 'v. make 的过去式/过去分词', example: 'I made a mistake.' },
  making: { word: 'making', phonetic: '/ˈmeɪkɪŋ/', definition: 'v. make 的现在分词 / n. 制作', example: 'He is making dinner.' },
  know: { word: 'know', phonetic: '/noʊ/', definition: 'v. 知道；认识', example: 'I know him.' },
  knows: { word: 'knows', phonetic: '/noʊz/', definition: 'v. know 的第三人称单数', example: 'She knows the answer.' },
  knew: { word: 'knew', phonetic: '/nuː/', definition: 'v. know 的过去式', example: 'I knew it!' },
  known: { word: 'known', phonetic: '/noʊn/', definition: 'v. know 的过去分词 / adj. 知名的', example: 'He is well known.' },
  knowing: { word: 'knowing', phonetic: '/ˈnoʊɪŋ/', definition: 'v. know 的现在分词 / adj. 会意的', example: 'A knowing smile.' },
  think: { word: 'think', phonetic: '/θɪŋk/', definition: 'v. 想；认为', example: 'I think so.' },
  thinks: { word: 'thinks', phonetic: '/θɪŋks/', definition: 'v. think 的第三人称单数', example: 'She thinks highly of you.' },
  thought: { word: 'thought', phonetic: '/θɔːt/', definition: 'v. think 的过去式/过去分词 / n. 想法', example: 'I thought about it.' },
  thinking: { word: 'thinking', phonetic: '/ˈθɪŋkɪŋ/', definition: 'v. think 的现在分词 / n. 思考', example: 'I am thinking.' },
  take: { word: 'take', phonetic: '/teɪk/', definition: 'v. 拿；花费；乘坐', example: 'Take a seat.' },
  takes: { word: 'takes', phonetic: '/teɪks/', definition: 'v. take 的第三人称单数', example: 'It takes time.' },
  took: { word: 'took', phonetic: '/tʊk/', definition: 'v. take 的过去式', example: 'I took a bus.' },
  taken: { word: 'taken', phonetic: '/ˈteɪkən/', definition: 'v. take 的过去分词', example: 'The seat is taken.' },
  taking: { word: 'taking', phonetic: '/ˈteɪkɪŋ/', definition: 'v. take 的现在分词 / n. 取得', example: 'I am taking a break.' },
  see: { word: 'see', phonetic: '/siː/', definition: 'v. 看见；理解', example: 'I see what you mean.' },
  sees: { word: 'sees', phonetic: '/siːz/', definition: 'v. see 的第三人称单数', example: 'She sees him.' },
  saw: { word: 'saw', phonetic: '/sɔː/', definition: 'v. see 的过去式', example: 'I saw a movie.' },
  seen: { word: 'seen', phonetic: '/siːn/', definition: 'v. see 的过去分词', example: 'Have you seen it?' },
  seeing: { word: 'seeing', phonetic: '/ˈsiːɪŋ/', definition: 'v. see 的现在分词 / n. 看见', example: 'I am seeing my doctor.' },
  come: { word: 'come', phonetic: '/kʌm/', definition: 'v. 来；变成', example: 'Come here!' },
  comes: { word: 'comes', phonetic: '/kʌmz/', definition: 'v. come 的第三人称单数', example: 'She comes early.' },
  came: { word: 'came', phonetic: '/keɪm/', definition: 'v. come 的过去式', example: 'He came late.' },
  coming: { word: 'coming', phonetic: '/ˈkʌmɪŋ/', definition: 'v. come 的现在分词 / adj. 即将到来的', example: 'I am coming!' },
  want: { word: 'want', phonetic: '/wɑːnt/', definition: 'v. 想要', example: 'I want water.' },
  wants: { word: 'wants', phonetic: '/wɑːnts/', definition: 'v. want 的第三人称单数', example: 'She wants to leave.' },
  wanted: { word: 'wanted', phonetic: '/ˈwɑːntɪd/', definition: 'v. want 的过去式/过去分词 / adj. 被通缉的', example: 'I wanted to help.' },
  wanting: { word: 'wanting', phonetic: '/ˈwɑːntɪŋ/', definition: 'v. want 的现在分词 / adj. 不足的', example: 'The meal was wanting.' },
  use: { word: 'use', phonetic: '/juːz/', definition: 'v. 使用 / n. 用途', example: 'Can I use your pen?' },
  uses: { word: 'uses', phonetic: '/ˈjuːzɪz/', definition: 'v. use 的第三人称单数', example: 'She uses a computer.' },
  used: { word: 'used', phonetic: '/juːzd/', definition: 'v. use 的过去式/过去分词 / adj. 二手的', example: 'I used to smoke.' },
  using: { word: 'using', phonetic: '/ˈjuːzɪŋ/', definition: 'v. use 的现在分词', example: 'I am using it.' },
  find: { word: 'find', phonetic: '/faɪnd/', definition: 'v. 找到；发现', example: 'I cannot find my keys.' },
  finds: { word: 'finds', phonetic: '/faɪndz/', definition: 'v. find 的第三人称单数', example: 'She finds it hard.' },
  found: { word: 'found', phonetic: '/faʊnd/', definition: 'v. find 的过去式/过去分词 / v. 建立', example: 'I found it!' },
  finding: { word: 'finding', phonetic: '/ˈfaɪndɪŋ/', definition: 'v. find 的现在分词 / n. 发现', example: 'The findings were published.' },
  give: { word: 'give', phonetic: '/ɡɪv/', definition: 'v. 给；赠送', example: 'Give me a hand.' },
  gives: { word: 'gives', phonetic: '/ɡɪvz/', definition: 'v. give 的第三人称单数', example: 'She gives advice.' },
  gave: { word: 'gave', phonetic: '/ɡeɪv/', definition: 'v. give 的过去式', example: 'He gave me a book.' },
  given: { word: 'given', phonetic: '/ˈɡɪvən/', definition: 'v. give 的过去分词 / prep. 鉴于', example: 'Given the circumstances...' },
  giving: { word: 'giving', phonetic: '/ˈɡɪvɪŋ/', definition: 'v. give 的现在分词 / n. 给予', example: 'Thank you for giving.' },
  tell: { word: 'tell', phonetic: '/tel/', definition: 'v. 告诉；辨别', example: 'Tell me the truth.' },
  tells: { word: 'tells', phonetic: '/telz/', definition: 'v. tell 的第三人称单数', example: 'She tells stories.' },
  told: { word: 'told', phonetic: '/toʊld/', definition: 'v. tell 的过去式/过去分词', example: 'I told you so.' },
  telling: { word: 'telling', phonetic: '/ˈtelɪŋ/', definition: 'v. tell 的现在分词 / adj. 有效的', example: 'A telling argument.' },
  work: { word: 'work', phonetic: '/wɜːrk/', definition: 'v. 工作；运转 / n. 工作', example: 'I work hard.' },
  works: { word: 'works', phonetic: '/wɜːrks/', definition: 'v. work 的第三人称单数 / n. 作品', example: 'She works in IT.' },
  worked: { word: 'worked', phonetic: '/wɜːrkt/', definition: 'v. work 的过去式/过去分词', example: 'I worked all day.' },
  working: { word: 'working', phonetic: '/ˈwɜːrkɪŋ/', definition: 'v. work 的现在分词 / adj. 工作的', example: 'I am working now.' },
  call: { word: 'call', phonetic: '/kɔːl/', definition: 'v. 打电话；称呼 / n. 电话', example: 'I will call you.' },
  calls: { word: 'calls', phonetic: '/kɔːlz/', definition: 'v. call 的第三人称单数', example: 'She calls me every day.' },
  called: { word: 'called', phonetic: '/kɔːld/', definition: 'v. call 的过去式/过去分词', example: 'He called my name.' },
  calling: { word: 'calling', phonetic: '/ˈkɔːlɪŋ/', definition: 'v. call 的现在分词 / n. 职业', example: 'Teaching is her calling.' },
  try: { word: 'try', phonetic: '/traɪ/', definition: 'v. 尝试；努力 / n. 尝试', example: 'Try again!' },
  tries: { word: 'tries', phonetic: '/traɪz/', definition: 'v. try 的第三人称单数', example: 'She tries her best.' },
  tried: { word: 'tried', phonetic: '/traɪd/', definition: 'v. try 的过去式/过去分词', example: 'I tried to help.' },
  trying: { word: 'trying', phonetic: '/ˈtraɪɪŋ/', definition: 'v. try 的现在分词 / adj. 令人难受的', example: 'It is trying times.' },
  need: { word: 'need', phonetic: '/niːd/', definition: 'v. 需要 / n. 需要', example: 'I need help.' },
  needs: { word: 'needs', phonetic: '/niːdz/', definition: 'v. need 的第三人称单数 / n. 需求', example: 'She needs rest.' },
  needed: { word: 'needed', phonetic: '/ˈniːdɪd/', definition: 'v. need 的过去式/过去分词', example: 'More time is needed.' },
  needing: { word: 'needing', phonetic: '/ˈniːdɪŋ/', definition: 'v. need 的现在分词', example: 'I am needing a break.' },
  feel: { word: 'feel', phonetic: '/fiːl/', definition: 'v. 感觉；触摸', example: 'I feel good.' },
  feels: { word: 'feels', phonetic: '/fiːlz/', definition: 'v. feel 的第三人称单数', example: 'She feels cold.' },
  felt: { word: 'felt', phonetic: '/felt/', definition: 'v. feel 的过去式/过去分词', example: 'I felt happy.' },
  feeling: { word: 'feeling', phonetic: '/ˈfiːlɪŋ/', definition: 'v. feel 的现在分词 / n. 感觉', example: 'I have a feeling.' },
  become: { word: 'become', phonetic: '/bɪˈkʌm/', definition: 'v. 变成；成为', example: 'It became clear.' },
  becomes: { word: 'becomes', phonetic: '/bɪˈkʌmz/', definition: 'v. become 的第三人称单数', example: 'She becomes angry.' },
  became: { word: 'became', phonetic: '/bɪˈkeɪm/', definition: 'v. become 的过去式', example: 'He became famous.' },
  becoming: { word: 'becoming', phonetic: '/bɪˈkʌmɪŋ/', definition: 'v. become 的现在分词 / adj. 合适的', example: 'A becoming dress.' },
  leave: { word: 'leave', phonetic: '/liːv/', definition: 'v. 离开；留下 / n. 假期', example: 'I must leave now.' },
  leaves: { word: 'leaves', phonetic: '/liːvz/', definition: 'v. leave 的第三人称单数 / n. 树叶（复数）', example: 'She leaves tomorrow.' },
  left: { word: 'left', phonetic: '/left/', definition: 'v. leave 的过去式/过去分词 / adj. 左边的', example: 'He left early.' },
  leaving: { word: 'leaving', phonetic: '/ˈliːvɪŋ/', definition: 'v. leave 的现在分词', example: 'I am leaving soon.' },
  put: { word: 'put', phonetic: '/pʊt/', definition: 'v. 放；放置', example: 'Put it down.' },
  puts: { word: 'puts', phonetic: '/pʊts/', definition: 'v. put 的第三人称单数', example: 'She puts on her coat.' },
  putting: { word: 'putting', phonetic: '/ˈpʊtɪŋ/', definition: 'v. put 的现在分词', example: 'I am putting it away.' },
  mean: { word: 'mean', phonetic: '/miːn/', definition: 'v. 意思是；打算 / adj. 吝啬的', example: 'What do you mean?' },
  means: { word: 'means', phonetic: '/miːnz/', definition: 'v. mean 的第三人称单数 / n. 方法', example: 'She means well.' },
  meant: { word: 'meant', phonetic: '/ment/', definition: 'v. mean 的过去式/过去分词', example: 'I meant no harm.' },
  meaning: { word: 'meaning', phonetic: '/ˈmiːnɪŋ/', definition: 'v. mean 的现在分词 / n. 意思', example: 'What is the meaning?' },
  keep: { word: 'keep', phonetic: '/kiːp/', definition: 'v. 保持；保留', example: 'Keep calm.' },
  keeps: { word: 'keeps', phonetic: '/kiːps/', definition: 'v. keep 的第三人称单数', example: 'She keeps a diary.' },
  kept: { word: 'kept', phonetic: '/kept/', definition: 'v. keep 的过去式/过去分词', example: 'I kept my promise.' },
  keeping: { word: 'keeping', phonetic: '/ˈkiːpɪŋ/', definition: 'v. keep 的现在分词 / n. 保管', example: 'In keeping with tradition.' },
  let: { word: 'let', phonetic: '/let/', definition: 'v. 让；允许', example: 'Let me help.' },
  lets: { word: 'lets', phonetic: '/lets/', definition: 'v. let 的第三人称单数', example: 'She lets me in.' },
  letting: { word: 'letting', phonetic: '/ˈletɪŋ/', definition: 'v. let 的现在分词 / n. 出租', example: 'I am letting go.' },
  begin: { word: 'begin', phonetic: '/bɪˈɡɪn/', definition: 'v. 开始', example: 'Let us begin!' },
  begins: { word: 'begins', phonetic: '/bɪˈɡɪnz/', definition: 'v. begin 的第三人称单数', example: 'The show begins now.' },
  began: { word: 'began', phonetic: '/bɪˈɡæn/', definition: 'v. begin 的过去式', example: 'It began to rain.' },
  begun: { word: 'begun', phonetic: '/bɪˈɡʌn/', definition: 'v. begin 的过去分词', example: 'Work has begun.' },
  beginning: { word: 'beginning', phonetic: '/bɪˈɡɪnɪŋ/', definition: 'v. begin 的现在分词 / n. 开始', example: 'In the beginning...' },
  seem: { word: 'seem', phonetic: '/siːm/', definition: 'v. 似乎；好像', example: 'You seem happy.' },
  seems: { word: 'seems', phonetic: '/siːmz/', definition: 'v. seem 的第三人称单数', example: 'It seems right.' },
  seemed: { word: 'seemed', phonetic: '/siːmd/', definition: 'v. seem 的过去式/过去分词', example: 'He seemed tired.' },
  seeming: { word: 'seeming', phonetic: '/ˈsiːmɪŋ/', definition: 'v. seem 的现在分词 / adj. 表面的', example: 'His seeming indifference.' },
  help: { word: 'help', phonetic: '/help/', definition: 'v. 帮助 / n. 帮助', example: 'Can you help me?' },
  helps: { word: 'helps', phonetic: '/helps/', definition: 'v. help 的第三人称单数', example: 'She helps others.' },
  helped: { word: 'helped', phonetic: '/helpt/', definition: 'v. help 的过去式/过去分词', example: 'I helped him.' },
  helping: { word: 'helping', phonetic: '/ˈhelpɪŋ/', definition: 'v. help 的现在分词 / n. 一份食物', example: 'A helping of rice.' },
  show: { word: 'show', phonetic: '/ʃoʊ/', definition: 'v. 展示；显示 / n. 节目', example: 'Show me how.' },
  shows: { word: 'shows', phonetic: '/ʃoʊz/', definition: 'v. show 的第三人称单数', example: 'She shows talent.' },
  showed: { word: 'showed', phonetic: '/ʃoʊd/', definition: 'v. show 的过去式', example: 'He showed me the way.' },
  shown: { word: 'shown', phonetic: '/ʃoʊn/', definition: 'v. show 的过去分词', example: 'It has been shown.' },
  showing: { word: 'showing', phonetic: '/ˈʃoʊɪŋ/', definition: 'v. show 的现在分词 / n. 放映', example: 'The showing is at 7.' },
  hear: { word: 'hear', phonetic: '/hɪr/', definition: 'v. 听见；听说', example: 'I hear you.' },
  hears: { word: 'hears', phonetic: '/hɪrz/', definition: 'v. hear 的第三人称单数', example: 'She hears music.' },
  heard: { word: 'heard', phonetic: '/hɜːrd/', definition: 'v. hear 的过去式/过去分词', example: 'I heard a noise.' },
  hearing: { word: 'hearing', phonetic: '/ˈhɪrɪŋ/', definition: 'v. hear 的现在分词 / n. 听力', example: 'I am hearing good things.' },
  play: { word: 'play', phonetic: '/pleɪ/', definition: 'v. 玩；演奏 / n. 戏剧', example: 'Let us play!' },
  plays: { word: 'plays', phonetic: '/pleɪz/', definition: 'v. play 的第三人称单数', example: 'She plays piano.' },
  played: { word: 'played', phonetic: '/pleɪd/', definition: 'v. play 的过去式/过去分词', example: 'We played games.' },
  playing: { word: 'playing', phonetic: '/ˈpleɪɪŋ/', definition: 'v. play 的现在分词 / n. 演奏', example: 'I enjoy playing tennis.' },
  run: { word: 'run', phonetic: '/rʌn/', definition: 'v. 跑；经营 / n. 跑步', example: 'I run every morning.' },
  runs: { word: 'runs', phonetic: '/rʌnz/', definition: 'v. run 的第三人称单数', example: 'She runs a business.' },
  ran: { word: 'ran', phonetic: '/ræn/', definition: 'v. run 的过去式', example: 'He ran fast.' },
  running: { word: 'running', phonetic: '/ˈrʌnɪŋ/', definition: 'v. run 的现在分词 / n. 跑步', example: 'I am running late.' },
  move: { word: 'move', phonetic: '/muːv/', definition: 'v. 移动；搬家 / n. 移动', example: 'Please move your car.' },
  moves: { word: 'moves', phonetic: '/muːvz/', definition: 'v. move 的第三人称单数', example: 'She moves gracefully.' },
  moved: { word: 'moved', phonetic: '/muːvd/', definition: 'v. move 的过去式/过去分词 / adj. 感动的', example: 'I was moved.' },
  moving: { word: 'moving', phonetic: '/ˈmuːvɪŋ/', definition: 'v. move 的现在分词 / adj. 感人的', example: 'A moving story.' },
  live: { word: 'live', phonetic: '/lɪv/', definition: 'v. 生活；居住 / adj. 现场的', example: 'I live in Beijing.' },
  lives: { word: 'lives', phonetic: '/lɪvz/', definition: 'v. live 的第三人称单数 / n. 生命（复数）', example: 'She lives alone.' },
  lived: { word: 'lived', phonetic: '/lɪvd/', definition: 'v. live 的过去式/过去分词', example: 'I lived there.' },
  living: { word: 'living', phonetic: '/ˈlɪvɪŋ/', definition: 'v. live 的现在分词 / n. 生计', example: 'I am living my dream.' },
  believe: { word: 'believe', phonetic: '/bɪˈliːv/', definition: 'v. 相信；认为', example: 'I believe you.' },
  believes: { word: 'believes', phonetic: '/bɪˈliːvz/', definition: 'v. believe 的第三人称单数', example: 'She believes in you.' },
  believed: { word: 'believed', phonetic: '/bɪˈliːvd/', definition: 'v. believe 的过去式/过去分词', example: 'I believed him.' },
  believing: { word: 'believing', phonetic: '/bɪˈliːvɪŋ/', definition: 'v. believe 的现在分词', example: 'Seeing is believing.' },
  bring: { word: 'bring', phonetic: '/brɪŋ/', definition: 'v. 带来；引起', example: 'Bring your friend.' },
  brings: { word: 'brings', phonetic: '/brɪŋz/', definition: 'v. bring 的第三人称单数', example: 'She brings joy.' },
  brought: { word: 'brought', phonetic: '/brɔːt/', definition: 'v. bring 的过去式/过去分词', example: 'He brought gifts.' },
  bringing: { word: 'bringing', phonetic: '/ˈbrɪŋɪŋ/', definition: 'v. bring 的现在分词', example: 'I am bringing food.' },
  happen: { word: 'happen', phonetic: '/ˈhæpən/', definition: 'v. 发生；碰巧', example: 'What happened?' },
  happens: { word: 'happens', phonetic: '/ˈhæpənz/', definition: 'v. happen 的第三人称单数', example: 'It happens.' },
  happened: { word: 'happened', phonetic: '/ˈhæpənd/', definition: 'v. happen 的过去式/过去分词', example: 'It happened yesterday.' },
  happening: { word: 'happening', phonetic: '/ˈhæpənɪŋ/', definition: 'v. happen 的现在分词 / n. 事件', example: 'What is happening?' },
  stand: { word: 'stand', phonetic: '/stænd/', definition: 'v. 站立；忍受 / n. 立场', example: 'Please stand up.' },
  stands: { word: 'stands', phonetic: '/stændz/', definition: 'v. stand 的第三人称单数', example: 'She stands tall.' },
  stood: { word: 'stood', phonetic: '/stʊd/', definition: 'v. stand 的过去式/过去分词', example: 'He stood there.' },
  standing: { word: 'standing', phonetic: '/ˈstændɪŋ/', definition: 'v. stand 的现在分词 / n. 地位', example: 'I have been standing.' },
  lose: { word: 'lose', phonetic: '/luːz/', definition: 'v. 丢失；输掉', example: 'Do not lose hope.' },
  loses: { word: 'loses', phonetic: '/ˈluːzɪz/', definition: 'v. lose 的第三人称单数', example: 'She loses her keys.' },
  lost: { word: 'lost', phonetic: '/lɔːst/', definition: 'v. lose 的过去式/过去分词 / adj. 迷路的', example: 'I lost my way.' },
  losing: { word: 'losing', phonetic: '/ˈluːzɪŋ/', definition: 'v. lose 的现在分词', example: 'I am losing patience.' },
  pay: { word: 'pay', phonetic: '/peɪ/', definition: 'v. 支付；偿还 / n. 工资', example: 'I will pay for dinner.' },
  pays: { word: 'pays', phonetic: '/peɪz/', definition: 'v. pay 的第三人称单数', example: 'She pays attention.' },
  paid: { word: 'paid', phonetic: '/peɪd/', definition: 'v. pay 的过去式/过去分词', example: 'I paid the bill.' },
  paying: { word: 'paying', phonetic: '/ˈpeɪɪŋ/', definition: 'v. pay 的现在分词', example: 'It is worth paying.' },
  meet: { word: 'meet', phonetic: '/miːt/', definition: 'v. 遇见；满足 / n. 会面', example: 'Nice to meet you.' },
  meets: { word: 'meets', phonetic: '/miːts/', definition: 'v. meet 的第三人称单数', example: 'She meets clients.' },
  met: { word: 'met', phonetic: '/met/', definition: 'v. meet 的过去式/过去分词', example: 'We met last year.' },
  meeting: { word: 'meeting', phonetic: '/ˈmiːtɪŋ/', definition: 'v. meet 的现在分词 / n. 会议', example: 'I am meeting him.' },
  include: { word: 'include', phonetic: '/ɪnˈkluːd/', definition: 'v. 包括；包含', example: 'Price includes tax.' },
  includes: { word: 'includes', phonetic: '/ɪnˈkluːdz/', definition: 'v. include 的第三人称单数', example: 'It includes everything.' },
  included: { word: 'included', phonetic: '/ɪnˈkluːdɪd/', definition: 'v. include 的过去式/过去分词', example: 'All are included.' },
  including: { word: 'including', phonetic: '/ɪnˈkluːdɪŋ/', definition: 'prep. 包括 / v. include 的现在分词', example: 'Everyone, including me.' },
  continue: { word: 'continue', phonetic: '/kənˈtɪnjuː/', definition: 'v. 继续', example: 'Please continue.' },
  continues: { word: 'continues', phonetic: '/kənˈtɪnjuːz/', definition: 'v. continue 的第三人称单数', example: 'The story continues.' },
  continued: { word: 'continued', phonetic: '/kənˈtɪnjuːd/', definition: 'v. continue 的过去式/过去分词', example: 'He continued walking.' },
  continuing: { word: 'continuing', phonetic: '/kənˈtɪnjuːɪŋ/', definition: 'v. continue 的现在分词', example: 'Continuing education.' },
  set: { word: 'set', phonetic: '/set/', definition: 'v. 设置；放置 / n. 集合', example: 'Set the table.' },
  sets: { word: 'sets', phonetic: '/sets/', definition: 'v. set 的第三人称单数', example: 'She sets goals.' },
  setting: { word: 'setting', phonetic: '/ˈsetɪŋ/', definition: 'v. set 的现在分词 / n. 环境', example: 'A beautiful setting.' },
  learn: { word: 'learn', phonetic: '/lɜːrn/', definition: 'v. 学习；得知', example: 'I want to learn.' },
  learns: { word: 'learns', phonetic: '/lɜːrnz/', definition: 'v. learn 的第三人称单数', example: 'She learns fast.' },
  learned: { word: 'learned', phonetic: '/ˈlɜːrnɪd/', definition: 'v. learn 的过去式/过去分词 / adj. 博学的', example: 'I learned a lot.' },
  learning: { word: 'learning', phonetic: '/ˈlɜːrnɪŋ/', definition: 'v. learn 的现在分词 / n. 学习', example: 'I am learning English.' },
  change: { word: 'change', phonetic: '/tʃeɪndʒ/', definition: 'v. 改变；更换 / n. 变化', example: 'Time for a change.' },
  changes: { word: 'changes', phonetic: '/ˈtʃeɪndʒɪz/', definition: 'v. change 的第三人称单数', example: 'She changes jobs.' },
  changed: { word: 'changed', phonetic: '/tʃeɪndʒd/', definition: 'v. change 的过去式/过去分词', example: 'I have changed.' },
  changing: { word: 'changing', phonetic: '/ˈtʃeɪndʒɪŋ/', definition: 'v. change 的现在分词', example: 'The changing seasons.' },
  lead: { word: 'lead', phonetic: '/liːd/', definition: 'v. 领导；导致 / n. 领导', example: 'Lead the way.' },
  leads: { word: 'leads', phonetic: '/liːdz/', definition: 'v. lead 的第三人称单数', example: 'She leads the team.' },
  led: { word: 'led', phonetic: '/led/', definition: 'v. lead 的过去式/过去分词', example: 'He led us home.' },
  leading: { word: 'leading', phonetic: '/ˈliːdɪŋ/', definition: 'v. lead 的现在分词 / adj. 领先的', example: 'A leading expert.' },
  understand: { word: 'understand', phonetic: '/ˌʌndərˈstænd/', definition: 'v. 理解；明白', example: 'I understand.' },
  understands: { word: 'understands', phonetic: '/ˌʌndərˈstændz/', definition: 'v. understand 的第三人称单数', example: 'She understands me.' },
  understood: { word: 'understood', phonetic: '/ˌʌndərˈstʊd/', definition: 'v. understand 的过去式/过去分词', example: 'I understood.' },
  understanding: { word: 'understanding', phonetic: '/ˌʌndərˈstændɪŋ/', definition: 'v. understand 的现在分词 / n. 理解', example: 'Thank you for understanding.' },
  watch: { word: 'watch', phonetic: '/wɑːtʃ/', definition: 'v. 观看；注视 / n. 手表', example: 'Watch TV.' },
  watches: { word: 'watches', phonetic: '/ˈwɑːtʃɪz/', definition: 'v. watch 的第三人称单数', example: 'She watches birds.' },
  watched: { word: 'watched', phonetic: '/wɑːtʃt/', definition: 'v. watch 的过去式/过去分词', example: 'I watched a movie.' },
  watching: { word: 'watching', phonetic: '/ˈwɑːtʃɪŋ/', definition: 'v. watch 的现在分词', example: 'I enjoy watching.' },
  follow: { word: 'follow', phonetic: '/ˈfɑːloʊ/', definition: 'v. 跟随；遵循', example: 'Follow me.' },
  follows: { word: 'follows', phonetic: '/ˈfɑːloʊz/', definition: 'v. follow 的第三人称单数', example: 'She follows rules.' },
  followed: { word: 'followed', phonetic: '/ˈfɑːloʊd/', definition: 'v. follow 的过去式/过去分词', example: 'I followed him.' },
  following: { word: 'following', phonetic: '/ˈfɑːloʊɪŋ/', definition: 'v. follow 的现在分词 / prep. 在...之后', example: 'The following day.' },
  stop: { word: 'stop', phonetic: '/stɑːp/', definition: 'v. 停止 / n. 车站', example: 'Stop talking!' },
  stops: { word: 'stops', phonetic: '/stɑːps/', definition: 'v. stop 的第三人称单数', example: 'She stops to rest.' },
  stopped: { word: 'stopped', phonetic: '/stɑːpt/', definition: 'v. stop 的过去式/过去分词', example: 'I stopped running.' },
  stopping: { word: 'stopping', phonetic: '/ˈstɑːpɪŋ/', definition: 'v. stop 的现在分词', example: 'I am stopping here.' },
  create: { word: 'create', phonetic: '/kriˈeɪt/', definition: 'v. 创造；创建', example: 'Create something new.' },
  creates: { word: 'creates', phonetic: '/kriˈeɪts/', definition: 'v. create 的第三人称单数', example: 'She creates art.' },
  created: { word: 'created', phonetic: '/kriˈeɪtɪd/', definition: 'v. create 的过去式/过去分词', example: 'God created the world.' },
  creating: { word: 'creating', phonetic: '/kriˈeɪtɪŋ/', definition: 'v. create 的现在分词', example: 'I am creating a plan.' },
  speak: { word: 'speak', phonetic: '/spiːk/', definition: 'v. 说话；演讲', example: 'Speak louder!' },
  speaks: { word: 'speaks', phonetic: '/spiːks/', definition: 'v. speak 的第三人称单数', example: 'She speaks French.' },
  spoke: { word: 'spoke', phonetic: '/spoʊk/', definition: 'v. speak 的过去式', example: 'He spoke to me.' },
  spoken: { word: 'spoken', phonetic: '/ˈspoʊkən/', definition: 'v. speak 的过去分词 / adj. 口头的', example: 'English is spoken here.' },
  speaking: { word: 'speaking', phonetic: '/ˈspiːkɪŋ/', definition: 'v. speak 的现在分词 / n. 演讲', example: 'I am speaking.' },
  read: { word: 'read', phonetic: '/riːd/', definition: 'v. 阅读', example: 'I like to read.' },
  reads: { word: 'reads', phonetic: '/riːdz/', definition: 'v. read 的第三人称单数', example: 'She reads every day.' },
  reading: { word: 'reading', phonetic: '/ˈriːdɪŋ/', definition: 'v. read 的现在分词 / n. 阅读', example: 'I am reading.' },
  allow: { word: 'allow', phonetic: '/əˈlaʊ/', definition: 'v. 允许；准许', example: 'Smoking is not allowed.' },
  allows: { word: 'allows', phonetic: '/əˈlaʊz/', definition: 'v. allow 的第三人称单数', example: 'She allows pets.' },
  allowed: { word: 'allowed', phonetic: '/əˈlaʊd/', definition: 'v. allow 的过去式/过去分词', example: 'I was allowed in.' },
  allowing: { word: 'allowing', phonetic: '/əˈlaʊɪŋ/', definition: 'v. allow 的现在分词', example: 'Allowing for errors.' },
  add: { word: 'add', phonetic: '/æd/', definition: 'v. 添加；增加', example: 'Add salt to taste.' },
  adds: { word: 'adds', phonetic: '/ædz/', definition: 'v. add 的第三人称单数', example: 'She adds sugar.' },
  added: { word: 'added', phonetic: '/ˈædɪd/', definition: 'v. add 的过去式/过去分词', example: 'I added water.' },
  adding: { word: 'adding', phonetic: '/ˈædɪŋ/', definition: 'v. add 的现在分词', example: 'I am adding more.' },
  spend: { word: 'spend', phonetic: '/spend/', definition: 'v. 花费；度过', example: 'Spend time wisely.' },
  spends: { word: 'spends', phonetic: '/spendz/', definition: 'v. spend 的第三人称单数', example: 'She spends money.' },
  spent: { word: 'spent', phonetic: '/spent/', definition: 'v. spend 的过去式/过去分词', example: 'I spent all day.' },
  spending: { word: 'spending', phonetic: '/ˈspendɪŋ/', definition: 'v. spend 的现在分词 / n. 开支', example: 'Government spending.' },
  grow: { word: 'grow', phonetic: '/ɡroʊ/', definition: 'v. 生长；种植；变得', example: 'Plants grow fast.' },
  grows: { word: 'grows', phonetic: '/ɡroʊz/', definition: 'v. grow 的第三人称单数', example: 'She grows vegetables.' },
  grew: { word: 'grew', phonetic: '/ɡruː/', definition: 'v. grow 的过去式', example: 'He grew taller.' },
  grown: { word: 'grown', phonetic: '/ɡroʊn/', definition: 'v. grow 的过去分词 / adj. 成年的', example: 'A grown man.' },
  growing: { word: 'growing', phonetic: '/ˈɡroʊɪŋ/', definition: 'v. grow 的现在分词 / adj. 增长的', example: 'A growing problem.' },
  open: { word: 'open', phonetic: '/ˈoʊpən/', definition: 'v. 打开 / adj. 开放的', example: 'Open the door.' },
  opens: { word: 'opens', phonetic: '/ˈoʊpənz/', definition: 'v. open 的第三人称单数', example: 'She opens the window.' },
  opened: { word: 'opened', phonetic: '/ˈoʊpənd/', definition: 'v. open 的过去式/过去分词', example: 'I opened the box.' },
  opening: { word: 'opening', phonetic: '/ˈoʊpənɪŋ/', definition: 'v. open 的现在分词 / n. 开口', example: 'The opening scene.' },
  walk: { word: 'walk', phonetic: '/wɔːk/', definition: 'v. 走；散步 / n. 步行', example: 'Let us walk.' },
  walks: { word: 'walks', phonetic: '/wɔːks/', definition: 'v. walk 的第三人称单数', example: 'She walks to school.' },
  walked: { word: 'walked', phonetic: '/wɔːkt/', definition: 'v. walk 的过去式/过去分词', example: 'I walked home.' },
  walking: { word: 'walking', phonetic: '/ˈwɔːkɪŋ/', definition: 'v. walk 的现在分词 / n. 散步', example: 'I enjoy walking.' },
  win: { word: 'win', phonetic: '/wɪn/', definition: 'v. 赢；获胜 / n. 胜利', example: 'I want to win.' },
  wins: { word: 'wins', phonetic: '/wɪnz/', definition: 'v. win 的第三人称单数', example: 'She wins again.' },
  won: { word: 'won', phonetic: '/wʌn/', definition: 'v. win 的过去式/过去分词', example: 'We won the game.' },
  winning: { word: 'winning', phonetic: '/ˈwɪnɪŋ/', definition: 'v. win 的现在分词 / adj. 迷人的', example: 'A winning smile.' },
  offer: { word: 'offer', phonetic: '/ˈɔːfər/', definition: 'v. 提供；出价 / n. 提议', example: 'Can I offer help?' },
  offers: { word: 'offers', phonetic: '/ˈɔːfərz/', definition: 'v. offer 的第三人称单数', example: 'She offers advice.' },
  offered: { word: 'offered', phonetic: '/ˈɔːfərd/', definition: 'v. offer 的过去式/过去分词', example: 'He offered coffee.' },
  offering: { word: 'offering', phonetic: '/ˈɔːfərɪŋ/', definition: 'v. offer 的现在分词 / n. 祭品', example: 'Thank you for offering.' },
  remember: { word: 'remember', phonetic: '/rɪˈmembər/', definition: 'v. 记得；记住', example: 'I remember you.' },
  remembers: { word: 'remembers', phonetic: '/rɪˈmembərz/', definition: 'v. remember 的第三人称单数', example: 'She remembers everything.' },
  remembered: { word: 'remembered', phonetic: '/rɪˈmembərd/', definition: 'v. remember 的过去式/过去分词', example: 'I remembered his name.' },
  remembering: { word: 'remembering', phonetic: '/rɪˈmembərɪŋ/', definition: 'v. remember 的现在分词', example: 'Remembering the past.' },
  love: { word: 'love', phonetic: '/lʌv/', definition: 'v. 爱；热爱 / n. 爱', example: 'I love you.' },
  loves: { word: 'loves', phonetic: '/lʌvz/', definition: 'v. love 的第三人称单数', example: 'She loves music.' },
  loved: { word: 'loved', phonetic: '/lʌvd/', definition: 'v. love 的过去式/过去分词', example: 'I loved the movie.' },
  loving: { word: 'loving', phonetic: '/ˈlʌvɪŋ/', definition: 'v. love 的现在分词 / adj. 慈爱的', example: 'A loving mother.' },
  consider: { word: 'consider', phonetic: '/kənˈsɪdər/', definition: 'v. 考虑；认为', example: 'Consider this option.' },
  considers: { word: 'considers', phonetic: '/kənˈsɪdərz/', definition: 'v. consider 的第三人称单数', example: 'She considers leaving.' },
  considered: { word: 'considered', phonetic: '/kənˈsɪdərd/', definition: 'v. consider 的过去式/过去分词', example: 'I considered it.' },
  considering: { word: 'considering', phonetic: '/kənˈsɪdərɪŋ/', definition: 'v. consider 的现在分词 / prep. 鉴于', example: 'Considering the cost...' },
  appear: { word: 'appear', phonetic: '/əˈpɪr/', definition: 'v. 出现；似乎', example: 'He appeared suddenly.' },
  appears: { word: 'appears', phonetic: '/əˈpɪrz/', definition: 'v. appear 的第三人称单数', example: 'She appears happy.' },
  appeared: { word: 'appeared', phonetic: '/əˈpɪrd/', definition: 'v. appear 的过去式/过去分词', example: 'He appeared on TV.' },
  appearing: { word: 'appearing', phonetic: '/əˈpɪrɪŋ/', definition: 'v. appear 的现在分词', example: 'A disappearing act.' },
  buy: { word: 'buy', phonetic: '/baɪ/', definition: 'v. 买；购买', example: 'I want to buy this.' },
  buys: { word: 'buys', phonetic: '/baɪz/', definition: 'v. buy 的第三人称单数', example: 'She buys groceries.' },
  bought: { word: 'bought', phonetic: '/bɔːt/', definition: 'v. buy 的过去式/过去分词', example: 'I bought a car.' },
  buying: { word: 'buying', phonetic: '/ˈbaɪɪŋ/', definition: 'v. buy 的现在分词', example: 'I am buying milk.' },
  wait: { word: 'wait', phonetic: '/weɪt/', definition: 'v. 等待 / n. 等待', example: 'Wait for me!' },
  waits: { word: 'waits', phonetic: '/weɪts/', definition: 'v. wait 的第三人称单数', example: 'She waits patiently.' },
  waited: { word: 'waited', phonetic: '/ˈweɪtɪd/', definition: 'v. wait 的过去式/过去分词', example: 'I waited an hour.' },
  waiting: { word: 'waiting', phonetic: '/ˈweɪtɪŋ/', definition: 'v. wait 的现在分词 / n. 等待', example: 'I am waiting.' },
  serve: { word: 'serve', phonetic: '/sɜːrv/', definition: 'v. 服务；供应', example: 'Serve the customers.' },
  serves: { word: 'serves', phonetic: '/sɜːrvz/', definition: 'v. serve 的第三人称单数', example: 'She serves dinner.' },
  served: { word: 'served', phonetic: '/sɜːrvd/', definition: 'v. serve 的过去式/过去分词', example: 'I served in the army.' },
  serving: { word: 'serving', phonetic: '/ˈsɜːrvɪŋ/', definition: 'v. serve 的现在分词 / n. 一份食物', example: 'A serving of rice.' },
  die: { word: 'die', phonetic: '/daɪ/', definition: 'v. 死亡；熄灭', example: 'Plants die without water.' },
  dies: { word: 'dies', phonetic: '/daɪz/', definition: 'v. die 的第三人称单数', example: 'The engine dies.' },
  died: { word: 'died', phonetic: '/daɪd/', definition: 'v. die 的过去式/过去分词', example: 'He died in 1999.' },
  dying: { word: 'dying', phonetic: '/ˈdaɪɪŋ/', definition: 'v. die 的现在分词 / adj. 临终的', example: 'A dying tradition.' },
  send: { word: 'send', phonetic: '/send/', definition: 'v. 发送；派遣', example: 'Send me an email.' },
  sends: { word: 'sends', phonetic: '/sendz/', definition: 'v. send 的第三人称单数', example: 'She sends gifts.' },
  sent: { word: 'sent', phonetic: '/sent/', definition: 'v. send 的过去式/过去分词', example: 'I sent a letter.' },
  sending: { word: 'sending', phonetic: '/ˈsendɪŋ/', definition: 'v. send 的现在分词', example: 'I am sending a package.' },
  expect: { word: 'expect', phonetic: '/ɪkˈspekt/', definition: 'v. 期望；预料', example: 'I expect good results.' },
  expects: { word: 'expects', phonetic: '/ɪkˈspekts/', definition: 'v. expect 的第三人称单数', example: 'She expects too much.' },
  expected: { word: 'expected', phonetic: '/ɪkˈspektɪd/', definition: 'v. expect 的过去式/过去分词', example: 'It was expected.' },
  expecting: { word: 'expecting', phonetic: '/ɪkˈspektɪŋ/', definition: 'v. expect 的现在分词', example: 'I am expecting a call.' },
  build: { word: 'build', phonetic: '/bɪld/', definition: 'v. 建造；建立', example: 'Build a house.' },
  builds: { word: 'builds', phonetic: '/bɪldz/', definition: 'v. build 的第三人称单数', example: 'She builds models.' },
  built: { word: 'built', phonetic: '/bɪlt/', definition: 'v. build 的过去式/过去分词', example: 'He built a bridge.' },
  building: { word: 'building', phonetic: '/ˈbɪldɪŋ/', definition: 'v. build 的现在分词 / n. 建筑物', example: 'A tall building.' },
  stay: { word: 'stay', phonetic: '/steɪ/', definition: 'v. 停留；保持 / n. 逗留', example: 'Stay here!' },
  stays: { word: 'stays', phonetic: '/steɪz/', definition: 'v. stay 的第三人称单数', example: 'She stays home.' },
  stayed: { word: 'stayed', phonetic: '/steɪd/', definition: 'v. stay 的过去式/过去分词', example: 'I stayed up late.' },
  staying: { word: 'staying', phonetic: '/ˈsteɪɪŋ/', definition: 'v. stay 的现在分词', example: 'I am staying here.' },
  fall: { word: 'fall', phonetic: '/fɔːl/', definition: 'v. 落下；跌倒 / n. 秋天', example: 'Leaves fall in autumn.' },
  falls: { word: 'falls', phonetic: '/fɔːlz/', definition: 'v. fall 的第三人称单数', example: 'She falls down.' },
  fell: { word: 'fell', phonetic: '/fel/', definition: 'v. fall 的过去式', example: 'He fell asleep.' },
  fallen: { word: 'fallen', phonetic: '/ˈfɔːlən/', definition: 'v. fall 的过去分词 / adj. 倒下的', example: 'A fallen hero.' },
  falling: { word: 'falling', phonetic: '/ˈfɔːlɪŋ/', definition: 'v. fall 的现在分词', example: 'Falling leaves.' },
  cut: { word: 'cut', phonetic: '/kʌt/', definition: 'v. 切；割 / n. 伤口', example: 'Cut the paper.' },
  cuts: { word: 'cuts', phonetic: '/kʌts/', definition: 'v. cut 的第三人称单数', example: 'She cuts hair.' },
  cutting: { word: 'cutting', phonetic: '/ˈkʌtɪŋ/', definition: 'v. cut 的现在分词 / n. 剪报', example: 'A cutting remark.' },
  reach: { word: 'reach', phonetic: '/riːtʃ/', definition: 'v. 到达；伸手 / n. 范围', example: 'Reach for the stars.' },
  reaches: { word: 'reaches', phonetic: '/ˈriːtʃɪz/', definition: 'v. reach 的第三人称单数', example: 'She reaches out.' },
  reached: { word: 'reached', phonetic: '/riːtʃt/', definition: 'v. reach 的过去式/过去分词', example: 'I reached the top.' },
  reaching: { word: 'reaching', phonetic: '/ˈriːtʃɪŋ/', definition: 'v. reach 的现在分词', example: 'Reaching for the sky.' },
  kill: { word: 'kill', phonetic: '/kɪl/', definition: 'v. 杀死；扼杀 / n. 猎获物', example: 'Smoking kills.' },
  kills: { word: 'kills', phonetic: '/kɪlz/', definition: 'v. kill 的第三人称单数', example: 'She kills time.' },
  killed: { word: 'killed', phonetic: '/kɪld/', definition: 'v. kill 的过去式/过去分词', example: 'He killed the spider.' },
  killing: { word: 'killing', phonetic: '/ˈkɪlɪŋ/', definition: 'v. kill 的现在分词 / n. 谋杀', example: 'A killing spree.' },
  remain: { word: 'remain', phonetic: '/rɪˈmeɪn/', definition: 'v. 保持；留下', example: 'Please remain seated.' },
  remains: { word: 'remains', phonetic: '/rɪˈmeɪnz/', definition: 'v. remain 的第三人称单数 / n. 遗迹', example: 'She remains calm.' },
  remained: { word: 'remained', phonetic: '/rɪˈmeɪnd/', definition: 'v. remain 的过去式/过去分词', example: 'He remained silent.' },
  remaining: { word: 'remaining', phonetic: '/rɪˈmeɪnɪŋ/', definition: 'v. remain 的现在分词 / adj. 剩余的', example: 'The remaining time.' },
  suggest: { word: 'suggest', phonetic: '/səɡˈdʒest/', definition: 'v. 建议；暗示', example: 'I suggest we wait.' },
  suggests: { word: 'suggests', phonetic: '/səɡˈdʒests/', definition: 'v. suggest 的第三人称单数', example: 'She suggests tea.' },
  suggested: { word: 'suggested', phonetic: '/səɡˈdʒestɪd/', definition: 'v. suggest 的过去式/过去分词', example: 'He suggested a plan.' },
  suggesting: { word: 'suggesting', phonetic: '/səɡˈdʒestɪŋ/', definition: 'v. suggest 的现在分词', example: 'Suggesting a solution.' },
  raise: { word: 'raise', phonetic: '/reɪz/', definition: 'v. 举起；筹集；养育', example: 'Raise your hand.' },
  raises: { word: 'raises', phonetic: '/ˈreɪzɪz/', definition: 'v. raise 的第三人称单数', example: 'She raises cattle.' },
  raised: { word: 'raised', phonetic: '/reɪzd/', definition: 'v. raise 的过去式/过去分词', example: 'I raised my voice.' },
  raising: { word: 'raising', phonetic: '/ˈreɪzɪŋ/', definition: 'v. raise 的现在分词', example: 'Raising children.' },
  pass: { word: 'pass', phonetic: '/pæs/', definition: 'v. 通过；传递 / n. 通行证', example: 'Pass the salt.' },
  passes: { word: 'passes', phonetic: '/ˈpæsɪz/', definition: 'v. pass 的第三人称单数', example: 'She passes the test.' },
  passed: { word: 'passed', phonetic: '/pæst/', definition: 'v. pass 的过去式/过去分词', example: 'He passed away.' },
  passing: { word: 'passing', phonetic: '/ˈpæsɪŋ/', definition: 'v. pass 的现在分词 / adj. 短暂的', example: 'A passing thought.' },
  sell: { word: 'sell', phonetic: '/sel/', definition: 'v. 卖；销售', example: 'Sell your car.' },
  sells: { word: 'sells', phonetic: '/selz/', definition: 'v. sell 的第三人称单数', example: 'She sells flowers.' },
  sold: { word: 'sold', phonetic: '/soʊld/', definition: 'v. sell 的过去式/过去分词', example: 'I sold my bike.' },
  selling: { word: 'selling', phonetic: '/ˈselɪŋ/', definition: 'v. sell 的现在分词 / n. 销售', example: 'Best-selling book.' },
  require: { word: 'require', phonetic: '/rɪˈkwaɪər/', definition: 'v. 需要；要求', example: 'This job requires skill.' },
  requires: { word: 'requires', phonetic: '/rɪˈkwaɪərz/', definition: 'v. require 的第三人称单数', example: 'She requires help.' },
  required: { word: 'required', phonetic: '/rɪˈkwaɪərd/', definition: 'v. require 的过去式/过去分词 / adj. 必需的', example: 'A required course.' },
  requiring: { word: 'requiring', phonetic: '/rɪˈkwaɪərɪŋ/', definition: 'v. require 的现在分词', example: 'Requiring attention.' },
  report: { word: 'report', phonetic: '/rɪˈpɔːrt/', definition: 'v. 报告；报道 / n. 报告', example: 'Report to duty.' },
  reports: { word: 'reports', phonetic: '/rɪˈpɔːrts/', definition: 'v. report 的第三人称单数', example: 'She reports news.' },
  reported: { word: 'reported', phonetic: '/rɪˈpɔːrtɪd/', definition: 'v. report 的过去式/过去分词', example: 'He reported the incident.' },
  reporting: { word: 'reporting', phonetic: '/rɪˈpɔːrtɪŋ/', definition: 'v. report 的现在分词 / n. 报道', example: 'News reporting.' },
  decide: { word: 'decide', phonetic: '/dɪˈsaɪd/', definition: 'v. 决定；判决', example: 'Decide for yourself.' },
  decides: { word: 'decides', phonetic: '/dɪˈsaɪdz/', definition: 'v. decide 的第三人称单数', example: 'She decides quickly.' },
  decided: { word: 'decided', phonetic: '/dɪˈsaɪdɪd/', definition: 'v. decide 的过去式/过去分词', example: 'I decided to stay.' },
  deciding: { word: 'deciding', phonetic: '/dɪˈsaɪdɪŋ/', definition: 'v. decide 的现在分词', example: 'The deciding factor.' },
  pull: { word: 'pull', phonetic: '/pʊl/', definition: 'v. 拉；拖 / n. 拉力', example: 'Pull the door.' },
  pulls: { word: 'pulls', phonetic: '/pʊlz/', definition: 'v. pull 的第三人称单数', example: 'She pulls the cart.' },
  pulled: { word: 'pulled', phonetic: '/pʊld/', definition: 'v. pull 的过去式/过去分词', example: 'He pulled the trigger.' },
  pulling: { word: 'pulling', phonetic: '/ˈpʊlɪŋ/', definition: 'v. pull 的现在分词', example: 'Pulling teeth.' },
  the: { word: 'the', phonetic: '/ðə/', definition: 'art. 这；那（定冠词）', example: 'The sun is shining.' },
  a: { word: 'a', phonetic: '/ə/', definition: 'art. 一（个）', example: 'A cup of tea.' },
  an: { word: 'an', phonetic: '/æn/', definition: 'art. 一（个，用于元音前）', example: 'An apple a day.' },
  and: { word: 'and', phonetic: '/ænd/', definition: 'conj. 和；而且', example: 'You and me.' },
  but: { word: 'but', phonetic: '/bʌt/', definition: 'conj. 但是；除了', example: 'Small but mighty.' },
  or: { word: 'or', phonetic: '/ɔːr/', definition: 'conj. 或者；否则', example: 'Tea or coffee?' },
  if: { word: 'if', phonetic: '/ɪf/', definition: 'conj. 如果；是否', example: 'If it rains...' },
  because: { word: 'because', phonetic: '/bɪˈkɔːz/', definition: 'conj. 因为', example: 'Because I said so.' },
  as: { word: 'as', phonetic: '/æz/', definition: 'conj./prep. 像；作为；当', example: 'As you wish.' },
  until: { word: 'until', phonetic: '/ənˈtɪl/', definition: 'conj./prep. 直到', example: 'Wait until tomorrow.' },
  while: { word: 'while', phonetic: '/waɪl/', definition: 'conj. 当...时；然而 / n. 一会儿', example: 'While you were out...' },
  of: { word: 'of', phonetic: '/əv/', definition: 'prep. ...的', example: 'A cup of tea.' },
  at: { word: 'at', phonetic: '/æt/', definition: 'prep. 在；以', example: 'At home.' },
  by: { word: 'by', phonetic: '/baɪ/', definition: 'prep. 通过；在...旁边', example: 'By car.' },
  for: { word: 'for', phonetic: '/fɔːr/', definition: 'prep. 为了；对于', example: 'For you.' },
  with: { word: 'with', phonetic: '/wɪð/', definition: 'prep. 和...一起；用', example: 'Come with me.' },
  about: { word: 'about', phonetic: '/əˈbaʊt/', definition: 'prep. 关于；大约', example: 'Tell me about it.' },
  into: { word: 'into', phonetic: '/ˈɪntuː/', definition: 'prep. 进入', example: 'Go into the room.' },
  through: { word: 'through', phonetic: '/θruː/', definition: 'prep. 穿过；通过', example: 'Walk through the park.' },
  during: { word: 'during', phonetic: '/ˈdjʊərɪŋ/', definition: 'prep. 在...期间', example: 'During the night.' },
  before: { word: 'before', phonetic: '/bɪˈfɔːr/', definition: 'prep./conj. 在...之前', example: 'Before dinner.' },
  after: { word: 'after', phonetic: '/ˈæftər/', definition: 'prep./conj. 在...之后', example: 'After school.' },
  above: { word: 'above', phonetic: '/əˈbʌv/', definition: 'prep./adv. 在...上方', example: 'Above the clouds.' },
  below: { word: 'below', phonetic: '/bɪˈloʊ/', definition: 'prep./adv. 在...下方', example: 'Below zero.' },
  up: { word: 'up', phonetic: '/ʌp/', definition: 'adv./prep. 向上', example: 'Stand up!' },
  down: { word: 'down', phonetic: '/daʊn/', definition: 'adv./prep. 向下', example: 'Sit down.' },
  in: { word: 'in', phonetic: '/ɪn/', definition: 'prep./adv. 在...里面', example: 'In the box.' },
  out: { word: 'out', phonetic: '/aʊt/', definition: 'adv./prep. 出去；在外', example: 'Go out!' },
  on: { word: 'on', phonetic: '/ɑːn/', definition: 'prep./adv. 在...上面', example: 'On the table.' },
  off: { word: 'off', phonetic: '/ɔːf/', definition: 'adv./prep. 离开；关掉', example: 'Turn off the light.' },
  over: { word: 'over', phonetic: '/ˈoʊvər/', definition: 'prep./adv. 在...上方；结束', example: 'Game over.' },
  under: { word: 'under', phonetic: '/ˈʌndər/', definition: 'prep./adv. 在...下面', example: 'Under the bed.' },
  again: { word: 'again', phonetic: '/əˈɡen/', definition: 'adv. 再一次', example: 'Try again.' },
  further: { word: 'further', phonetic: '/ˈfɜːrðər/', definition: 'adv./adj. 更远；进一步', example: 'Further away.' },
  then: { word: 'then', phonetic: '/ðen/', definition: 'adv. 然后；那么', example: 'First this, then that.' },
  once: { word: 'once', phonetic: '/wʌns/', definition: 'adv. 一次；曾经', example: 'Once upon a time.' },
  here: { word: 'here', phonetic: '/hɪr/', definition: 'adv. 这里', example: 'Come here!' },
  there: { word: 'there', phonetic: '/ðer/', definition: 'adv. 那里', example: 'Over there.' },
  when: { word: 'when', phonetic: '/wen/', definition: 'adv./conj. 什么时候；当...时', example: 'When will you go?' },
  where: { word: 'where', phonetic: '/wer/', definition: 'adv./conj. 在哪里', example: 'Where are you?' },
  why: { word: 'why', phonetic: '/waɪ/', definition: 'adv. 为什么', example: 'Why not?' },
  how: { word: 'how', phonetic: '/haʊ/', definition: 'adv. 如何；多么', example: 'How are you?' },
  both: { word: 'both', phonetic: '/boʊθ/', definition: 'det./pron. 两者都', example: 'Both of them.' },
  few: { word: 'few', phonetic: '/fjuː/', definition: 'det./pron. 很少', example: 'A few friends.' },
  more: { word: 'more', phonetic: '/mɔːr/', definition: 'det./pron./adv. 更多', example: 'More please.' },
  most: { word: 'most', phonetic: '/moʊst/', definition: 'det./pron./adv. 最多；大多数', example: 'Most people.' },
  no: { word: 'no', phonetic: '/noʊ/', definition: 'det. 没有 / adv. 不', example: 'No problem.' },
  nor: { word: 'nor', phonetic: '/nɔːr/', definition: 'conj. 也不', example: 'Neither here nor there.' },
  not: { word: 'not', phonetic: '/nɑːt/', definition: 'adv. 不', example: 'Do not go.' },
  only: { word: 'only', phonetic: '/ˈoʊnli/', definition: 'adv. 只有 / adj. 唯一的', example: 'Only you.' },
  own: { word: 'own', phonetic: '/oʊn/', definition: 'adj./v. 自己的；拥有', example: 'My own car.' },
  same: { word: 'same', phonetic: '/seɪm/', definition: 'adj./pron. 相同的', example: 'The same thing.' },
  so: { word: 'so', phonetic: '/soʊ/', definition: 'adv. 如此；所以', example: 'So beautiful!' },
  than: { word: 'than', phonetic: '/ðæn/', definition: 'conj. 比', example: 'Better than ever.' },
  too: { word: 'too', phonetic: '/tuː/', definition: 'adv. 也；太', example: 'Me too.' },
  very: { word: 'very', phonetic: '/ˈveri/', definition: 'adv. 非常', example: 'Very good.' },
  just: { word: 'just', phonetic: '/dʒʌst/', definition: 'adv. 刚刚；只是', example: 'Just a minute.' },
  now: { word: 'now', phonetic: '/naʊ/', definition: 'adv. 现在', example: 'Do it now!' },
  also: { word: 'also', phonetic: '/ˈɔːlsoʊ/', definition: 'adv. 也', example: 'I also agree.' },
  back: { word: 'back', phonetic: '/bæk/', definition: 'adv./n. 向后；背部', example: 'Come back!' },
  still: { word: 'still', phonetic: '/stɪl/', definition: 'adv. 仍然 / adj. 静止的', example: 'Still water.' },
  even: { word: 'even', phonetic: '/ˈiːvn/', definition: 'adv. 甚至 / adj. 平坦的', example: 'Even better.' },
  good: { word: 'good', phonetic: '/ɡʊd/', definition: 'adj. 好的 / n. 善行', example: 'Good morning!' },
  new: { word: 'new', phonetic: '/nuː/', definition: 'adj. 新的', example: 'A new day.' },
  first: { word: 'first', phonetic: '/fɜːrst/', definition: 'adj./adv. 第一', example: 'First place.' },
  last: { word: 'last', phonetic: '/læst/', definition: 'adj./adv. 最后；上一个', example: 'Last night.' },
  long: { word: 'long', phonetic: '/lɔːŋ/', definition: 'adj. 长的 / v. 渴望', example: 'A long time.' },
  great: { word: 'great', phonetic: '/ɡreɪt/', definition: 'adj. 伟大的；极好的', example: 'Great job!' },
  little: { word: 'little', phonetic: '/ˈlɪtl/', definition: 'adj./adv. 小的；少的', example: 'A little bit.' },
  old: { word: 'old', phonetic: '/oʊld/', definition: 'adj. 老的；旧的', example: 'An old friend.' },
  right: { word: 'right', phonetic: '/raɪt/', definition: 'adj./adv. 正确的；右边', example: 'That is right.' },
  big: { word: 'big', phonetic: '/bɪɡ/', definition: 'adj. 大的', example: 'A big house.' },
  high: { word: 'high', phonetic: '/haɪ/', definition: 'adj./adv. 高的', example: 'High quality.' },
  different: { word: 'different', phonetic: '/ˈdɪfrənt/', definition: 'adj. 不同的', example: 'Different from.' },
  small: { word: 'small', phonetic: '/smɔːl/', definition: 'adj. 小的', example: 'A small world.' },
  large: { word: 'large', phonetic: '/lɑːrdʒ/', definition: 'adj. 大的', example: 'A large number.' },
  next: { word: 'next', phonetic: '/nekst/', definition: 'adj./adv. 下一个', example: 'Next time.' },
  early: { word: 'early', phonetic: '/ˈɜːrli/', definition: 'adj./adv. 早的', example: 'Early bird.' },
  young: { word: 'young', phonetic: '/jʌŋ/', definition: 'adj. 年轻的', example: 'Young people.' },
  important: { word: 'important', phonetic: '/ɪmˈpɔːrtnt/', definition: 'adj. 重要的', example: 'Very important.' },
  public: { word: 'public', phonetic: '/ˈpʌblɪk/', definition: 'adj. 公共的 / n. 公众', example: 'Public transport.' },
  bad: { word: 'bad', phonetic: '/bæd/', definition: 'adj. 坏的；严重的', example: 'Bad weather.' },
  able: { word: 'able', phonetic: '/ˈeɪbl/', definition: 'adj. 能够的', example: 'Able to do it.' },
  man: { word: 'man', phonetic: '/mæn/', definition: 'n. 男人；人类', example: 'A young man.' },
  woman: { word: 'woman', phonetic: '/ˈwʊmən/', definition: 'n. 女人', example: 'A beautiful woman.' },
  child: { word: 'child', phonetic: '/tʃaɪld/', definition: 'n. 孩子', example: 'A happy child.' },
  time: { word: 'time', phonetic: '/taɪm/', definition: 'n. 时间；次数 / v. 计时', example: 'What time is it?' },
  year: { word: 'year', phonetic: '/jɪr/', definition: 'n. 年', example: 'Happy new year!' },
  way: { word: 'way', phonetic: '/weɪ/', definition: 'n. 路；方法', example: 'Which way?' },
  day: { word: 'day', phonetic: '/deɪ/', definition: 'n. 天；白天', example: 'Have a nice day!' },
  thing: { word: 'thing', phonetic: '/θɪŋ/', definition: 'n. 事情；东西', example: 'One thing at a time.' },
  people: { word: 'people', phonetic: '/ˈpiːpl/', definition: 'n. 人们；民族', example: 'Many people.' },
  life: { word: 'life', phonetic: '/laɪf/', definition: 'n. 生活；生命', example: 'Way of life.' },
  world: { word: 'world', phonetic: '/wɜːrld/', definition: 'n. 世界', example: 'Around the world.' },
  hand: { word: 'hand', phonetic: '/hænd/', definition: 'n. 手 / v. 递给', example: 'Raise your hand.' },
  part: { word: 'part', phonetic: '/pɑːrt/', definition: 'n. 部分 / v. 分开', example: 'Part of it.' },
  eye: { word: 'eye', phonetic: '/aɪ/', definition: 'n. 眼睛 / v. 看', example: 'Keep an eye on.' },
  place: { word: 'place', phonetic: '/pleɪs/', definition: 'n. 地方 / v. 放置', example: 'A nice place.' },
  problem: { word: 'problem', phonetic: '/ˈprɑːbləm/', definition: 'n. 问题', example: 'No problem!' },
  fact: { word: 'fact', phonetic: '/fækt/', definition: 'n. 事实', example: 'In fact...' },
  point: { word: 'point', phonetic: '/pɔɪnt/', definition: 'n. 点；观点 / v. 指向', example: 'Good point.' },
  government: { word: 'government', phonetic: '/ˈɡʌvərnmənt/', definition: 'n. 政府', example: 'The local government.' },
  company: { word: 'company', phonetic: '/ˈkʌmpəni/', definition: 'n. 公司；陪伴', example: 'A big company.' },
  number: { word: 'number', phonetic: '/ˈnʌmbər/', definition: 'n. 数字；号码 / v. 编号', example: 'A large number.' },
  group: { word: 'group', phonetic: '/ɡruːp/', definition: 'n. 组；团体 / v. 分组', example: 'A music group.' },
  system: { word: 'system', phonetic: '/ˈsɪstəm/', definition: 'n. 系统', example: 'The solar system.' },
  program: { word: 'program', phonetic: '/ˈproʊɡræm/', definition: 'n. 程序；节目 / v. 编程', example: 'A TV program.' },
  question: { word: 'question', phonetic: '/ˈkwestʃən/', definition: 'n. 问题 / v. 询问', example: 'Good question.' },
  case: { word: 'case', phonetic: '/keɪs/', definition: 'n. 情况；案例；箱子', example: 'In that case...' },
  area: { word: 'area', phonetic: '/ˈeriə/', definition: 'n. 地区；面积', example: 'Rural area.' },
  money: { word: 'money', phonetic: '/ˈmʌni/', definition: 'n. 钱', example: 'Save money.' },
  story: { word: 'story', phonetic: '/ˈstɔːri/', definition: 'n. 故事；楼层', example: 'Tell me a story.' },
  night: { word: 'night', phonetic: '/naɪt/', definition: 'n. 夜晚', example: 'At night.' },
  lot: { word: 'lot', phonetic: '/lɑːt/', definition: 'n. 许多；命运 / adv. 很', example: 'A lot of.' },
  study: { word: 'study', phonetic: '/ˈstʌdi/', definition: 'n./v. 学习；研究', example: 'Study hard.' },
  book: { word: 'book', phonetic: '/bʊk/', definition: 'n. 书 / v. 预订', example: 'Read a book.' },
  job: { word: 'job', phonetic: '/dʒɑːb/', definition: 'n. 工作', example: 'A good job.' },
  word: { word: 'word', phonetic: '/wɜːrd/', definition: 'n. 单词；话语', example: 'In other words...' },
  business: { word: 'business', phonetic: '/ˈbɪznəs/', definition: 'n. 商业；生意', example: 'Mind your own business.' },
  issue: { word: 'issue', phonetic: '/ˈɪʃuː/', definition: 'n. 问题；发行 / v. 发行', example: 'A big issue.' },
  side: { word: 'side', phonetic: '/saɪd/', definition: 'n. 边；方面 / adj. 侧面的', example: 'On the side.' },
  kind: { word: 'kind', phonetic: '/kaɪnd/', definition: 'n. 种类 / adj. 善良的', example: 'What kind?' },
  head: { word: 'head', phonetic: '/hed/', definition: 'n. 头；领导 / v. 朝...行进', example: 'Headache.' },
  house: { word: 'house', phonetic: '/haʊs/', definition: 'n. 房子 / v. 容纳', example: 'A big house.' },
  service: { word: 'service', phonetic: '/ˈsɜːrvɪs/', definition: 'n. 服务 / v. 维修', example: 'Customer service.' },
  friend: { word: 'friend', phonetic: '/frend/', definition: 'n. 朋友', example: 'A true friend.' },
  father: { word: 'father', phonetic: '/ˈfɑːðər/', definition: 'n. 父亲 / v. 创立', example: 'My father.' },
  power: { word: 'power', phonetic: '/ˈpaʊər/', definition: 'n. 力量；权力 / v. 驱动', example: 'Electric power.' },
  hour: { word: 'hour', phonetic: '/ˈaʊər/', definition: 'n. 小时', example: 'An hour ago.' },
  game: { word: 'game', phonetic: '/ɡeɪm/', definition: 'n. 游戏；比赛', example: 'A fun game.' },
  line: { word: 'line', phonetic: '/laɪn/', definition: 'n. 线；行 / v. 排队', example: 'Wait in line.' },
  end: { word: 'end', phonetic: '/end/', definition: 'n. 结束；末端 / v. 结束', example: 'The end.' },
  member: { word: 'member', phonetic: '/ˈmembər/', definition: 'n. 成员', example: 'A team member.' },
  law: { word: 'law', phonetic: '/lɔː/', definition: 'n. 法律', example: 'Break the law.' },
  car: { word: 'car', phonetic: '/kɑːr/', definition: 'n. 汽车', example: 'A new car.' },
  city: { word: 'city', phonetic: '/ˈsɪti/', definition: 'n. 城市', example: 'A big city.' },
  community: { word: 'community', phonetic: '/kəˈmjuːnəti/', definition: 'n. 社区', example: 'Local community.' },
  name: { word: 'name', phonetic: '/neɪm/', definition: 'n. 名字 / v. 命名', example: 'My name is...' },
  president: { word: 'president', phonetic: '/ˈprezɪdənt/', definition: 'n. 总统；总裁', example: 'The president.' },
  team: { word: 'team', phonetic: '/tiːm/', definition: 'n. 团队 / v. 合作', example: 'Team work.' },
  minute: { word: 'minute', phonetic: '/ˈmɪnɪt/', definition: 'n. 分钟', example: 'Wait a minute.' },
  idea: { word: 'idea', phonetic: '/aɪˈdiːə/', definition: 'n. 想法；主意', example: 'Good idea!' },
  kid: { word: 'kid', phonetic: '/kɪd/', definition: 'n. 孩子 / v. 开玩笑', example: 'Just kidding!' },
  body: { word: 'body', phonetic: '/ˈbɑːdi/', definition: 'n. 身体；主体', example: 'Body language.' },
  information: { word: 'information', phonetic: '/ˌɪnfərˈmeɪʃn/', definition: 'n. 信息', example: 'For your information.' },
  parent: { word: 'parent', phonetic: '/ˈperənt/', definition: 'n. 父母', example: 'My parents.' },
  face: { word: 'face', phonetic: '/feɪs/', definition: 'n. 脸；表面 / v. 面对', example: 'Face the truth.' },
  others: { word: 'others', phonetic: '/ˈʌðərz/', definition: 'pron. 其他人', example: 'Help others.' },
  level: { word: 'level', phonetic: '/ˈlevl/', definition: 'n. 水平 / adj. 平坦的 / v. 使平坦', example: 'High level.' },
  office: { word: 'office', phonetic: '/ˈɔːfɪs/', definition: 'n. 办公室', example: 'At the office.' },
  door: { word: 'door', phonetic: '/dɔːr/', definition: 'n. 门', example: 'Open the door.' },
  health: { word: 'health', phonetic: '/helθ/', definition: 'n. 健康', example: 'Good health.' },
  person: { word: 'person', phonetic: '/ˈpɜːrsn/', definition: 'n. 人', example: 'A nice person.' },
  art: { word: 'art', phonetic: '/ɑːrt/', definition: 'n. 艺术', example: 'Work of art.' },
  war: { word: 'war', phonetic: '/wɔːr/', definition: 'n. 战争', example: 'At war.' },
  history: { word: 'history', phonetic: '/ˈhɪstri/', definition: 'n. 历史', example: 'Make history.' },
  party: { word: 'party', phonetic: '/ˈpɑːrti/', definition: 'n. 聚会；政党 / v. 狂欢', example: 'Birthday party.' },
  result: { word: 'result', phonetic: '/rɪˈzʌlt/', definition: 'n. 结果 / v. 导致', example: 'As a result...' },
  morning: { word: 'morning', phonetic: '/ˈmɔːrnɪŋ/', definition: 'n. 早晨', example: 'Good morning!' },
  reason: { word: 'reason', phonetic: '/ˈriːzn/', definition: 'n. 原因 / v. 推理', example: 'The reason why...' },
  research: { word: 'research', phonetic: '/rɪˈsɜːrtʃ/', definition: 'n./v. 研究', example: 'Do research.' },
  girl: { word: 'girl', phonetic: '/ɡɜːrl/', definition: 'n. 女孩', example: 'A little girl.' },
  guy: { word: 'guy', phonetic: '/ɡaɪ/', definition: 'n. 家伙；男人', example: 'That guy.' },
  moment: { word: 'moment', phonetic: '/ˈmoʊmənt/', definition: 'n. 时刻', example: 'Just a moment.' },
  air: { word: 'air', phonetic: '/er/', definition: 'n. 空气；神态 / v. 晾干', example: 'Fresh air.' },
  teacher: { word: 'teacher', phonetic: '/ˈtiːtʃər/', definition: 'n. 老师', example: 'My teacher.' },
  force: { word: 'force', phonetic: '/fɔːrs/', definition: 'n. 力量；军队 / v. 强迫', example: 'By force.' },
  education: { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', definition: 'n. 教育', example: 'Higher education.' },
  foot: { word: 'foot', phonetic: '/fʊt/', definition: 'n. 脚；英尺', example: 'On foot.' },
  boy: { word: 'boy', phonetic: '/bɔɪ/', definition: 'n. 男孩', example: 'A young boy.' },
  age: { word: 'age', phonetic: '/eɪdʒ/', definition: 'n. 年龄；时代 / v. 变老', example: 'At your age.' },
  policy: { word: 'policy', phonetic: '/ˈpɑːləsi/', definition: 'n. 政策', example: 'Public policy.' },
  everything: { word: 'everything', phonetic: '/ˈevriθɪŋ/', definition: 'pron. 一切', example: 'Everything is fine.' },
  process: { word: 'process', phonetic: '/ˈprɑːses/', definition: 'n. 过程 / v. 处理', example: 'In the process.' },
  music: { word: 'music', phonetic: '/ˈmjuːzɪk/', definition: 'n. 音乐', example: 'Listen to music.' },
  data: { word: 'data', phonetic: '/ˈdeɪtə/', definition: 'n. 数据', example: 'Big data.' },
  food: { word: 'food', phonetic: '/fuːd/', definition: 'n. 食物', example: 'Fast food.' },
  theory: { word: 'theory', phonetic: '/ˈθiːəri/', definition: 'n. 理论', example: 'In theory.' },
  nature: { word: 'nature', phonetic: '/ˈneɪtʃər/', definition: 'n. 自然；本质', example: 'Mother nature.' },
  industry: { word: 'industry', phonetic: '/ˈɪndəstri/', definition: 'n. 工业；行业', example: 'Film industry.' },
  material: { word: 'material', phonetic: '/məˈtɪriəl/', definition: 'n. 材料 / adj. 物质的', example: 'Raw material.' },
  human: { word: 'human', phonetic: '/ˈhjuːmən/', definition: 'n. 人类 / adj. 人的', example: 'Human rights.' },
  death: { word: 'death', phonetic: '/deθ/', definition: 'n. 死亡', example: 'Cause of death.' },
  experience: { word: 'experience', phonetic: '/ɪkˈspɪriəns/', definition: 'n. 经验；经历 / v. 经历', example: 'Work experience.' },
  effect: { word: 'effect', phonetic: '/ɪˈfekt/', definition: 'n. 影响；效果 / v. 实现', example: 'Side effect.' },
  class: { word: 'class', phonetic: '/klæs/', definition: 'n. 班级；阶级', example: 'In class.' },
  control: { word: 'control', phonetic: '/kənˈtroʊl/', definition: 'n./v. 控制', example: 'Under control.' },
  care: { word: 'care', phonetic: '/ker/', definition: 'n./v. 关心；照顾', example: 'Take care!' },
  field: { word: 'field', phonetic: '/fiːld/', definition: 'n. 田地；领域', example: 'In the field.' },
  development: { word: 'development', phonetic: '/dɪˈveləpmənt/', definition: 'n. 发展', example: 'Economic development.' },
  role: { word: 'role', phonetic: '/roʊl/', definition: 'n. 角色；作用', example: 'Leading role.' },
  effort: { word: 'effort', phonetic: '/ˈefərt/', definition: 'n. 努力', example: 'Make an effort.' },
  rate: { word: 'rate', phonetic: '/reɪt/', definition: 'n. 比率；速度 / v. 评价', example: 'Interest rate.' },
  heart: { word: 'heart', phonetic: '/hɑːrt/', definition: 'n. 心；中心', example: 'Heart attack.' },
  drug: { word: 'drug', phonetic: '/drʌɡ/', definition: 'n. 药物；毒品 / v. 使麻醉', example: 'Drug store.' },
  leader: { word: 'leader', phonetic: '/ˈliːdər/', definition: 'n. 领导', example: 'Team leader.' },
  light: { word: 'light', phonetic: '/laɪt/', definition: 'n. 光；灯 / adj. 轻的 / v. 点燃', example: 'Turn on the light.' },
  voice: { word: 'voice', phonetic: '/vɔɪs/', definition: 'n. 声音 / v. 表达', example: 'In a low voice.' },
  wife: { word: 'wife', phonetic: '/waɪf/', definition: 'n. 妻子', example: 'My wife.' },
  police: { word: 'police', phonetic: '/pəˈliːs/', definition: 'n. 警察', example: 'Call the police.' },
  mind: { word: 'mind', phonetic: '/maɪnd/', definition: 'n. 头脑 / v. 介意', example: 'Never mind.' },
  finally: { word: 'finally', phonetic: '/ˈfaɪnəli/', definition: 'adv. 最后', example: 'Finally done!' },
  return: { word: 'return', phonetic: '/rɪˈtɜːrn/', definition: 'v. 返回；归还 / n. 返回', example: 'Return home.' },
  explain: { word: 'explain', phonetic: '/ɪkˈspleɪn/', definition: 'v. 解释', example: 'Explain yourself.' },
  carry: { word: 'carry', phonetic: '/ˈkæri/', definition: 'v. 携带；搬运', example: 'Carry on!' },
  develop: { word: 'develop', phonetic: '/dɪˈveləp/', definition: 'v. 发展；开发', example: 'Develop skills.' },
  hope: { word: 'hope', phonetic: '/hoʊp/', definition: 'n./v. 希望', example: 'I hope so.' },
  drive: { word: 'drive', phonetic: '/draɪv/', definition: 'v. 驾驶；驱使 / n. 驱动力', example: 'Drive carefully.' },
  break: { word: 'break', phonetic: '/breɪk/', definition: 'v. 打破；休息 / n. 休息', example: 'Take a break.' },
  receive: { word: 'receive', phonetic: '/rɪˈsiːv/', definition: 'v. 收到；接待', example: 'Receive a gift.' },
  agree: { word: 'agree', phonetic: '/əˈɡriː/', definition: 'v. 同意', example: 'I agree with you.' },
  support: { word: 'support', phonetic: '/səˈpɔːrt/', definition: 'n./v. 支持', example: 'Support team.' },
  remove: { word: 'remove', phonetic: '/rɪˈmuːv/', definition: 'v. 移除；去掉', example: 'Remove the lid.' },
  describe: { word: 'describe', phonetic: '/dɪˈskraɪb/', definition: 'v. 描述', example: 'Describe it.' },
  thank: { word: 'thank', phonetic: '/θæŋk/', definition: 'v. 感谢 / n. 感谢', example: 'Thank you!' },
  sorry: { word: 'sorry', phonetic: '/ˈsɔːri/', definition: 'adj. 抱歉的', example: 'I am sorry.' },
  please: { word: 'please', phonetic: '/pliːz/', definition: 'adv. 请 / v. 使高兴', example: 'Please sit down.' },
  yes: { word: 'yes', phonetic: '/jes/', definition: 'adv. 是', example: 'Yes, please.' },
  ok: { word: 'OK', phonetic: '/ˌoʊˈkeɪ/', definition: 'adv./adj. 好的', example: 'That is OK.' },
  okay: { word: 'okay', phonetic: '/ˌoʊˈkeɪ/', definition: 'adv./adj. 好的', example: 'Okay, let us go.' },
  hello: { word: 'hello', phonetic: '/həˈloʊ/', definition: 'int. 你好', example: 'Hello there!' },
  hi: { word: 'hi', phonetic: '/haɪ/', definition: 'int. 嗨', example: 'Hi, how are you?' },
  bye: { word: 'bye', phonetic: '/baɪ/', definition: 'int. 再见', example: 'Bye bye!' },
  goodbye: { word: 'goodbye', phonetic: '/ˌɡʊdˈbaɪ/', definition: 'int. 再见', example: 'Say goodbye.' },
  thanks: { word: 'thanks', phonetic: '/θæŋks/', definition: 'n. 谢谢', example: 'Many thanks!' },
  welcome: { word: 'welcome', phonetic: '/ˈwelkəm/', definition: 'adj./int. 欢迎', example: 'You are welcome.' },
  zero: { word: 'zero', phonetic: '/ˈzɪəroʊ/', definition: 'num. 零', example: 'Zero tolerance.' },
  two: { word: 'two', phonetic: '/tuː/', definition: 'num. 二', example: 'Two apples.' },
  three: { word: 'three', phonetic: '/θriː/', definition: 'num. 三', example: 'Three times.' },
  four: { word: 'four', phonetic: '/fɔːr/', definition: 'num. 四', example: 'Four seasons.' },
  five: { word: 'five', phonetic: '/faɪv/', definition: 'num. 五', example: 'Five minutes.' },
  six: { word: 'six', phonetic: '/sɪks/', definition: 'num. 六', example: 'Six o clock.' },
  seven: { word: 'seven', phonetic: '/ˈsevn/', definition: 'num. 七', example: 'Seven days.' },
  eight: { word: 'eight', phonetic: '/eɪt/', definition: 'num. 八', example: 'Eight hours.' },
  nine: { word: 'nine', phonetic: '/naɪn/', definition: 'num. 九', example: 'Nine lives.' },
  ten: { word: 'ten', phonetic: '/ten/', definition: 'num. 十', example: 'Ten years.' },
  hundred: { word: 'hundred', phonetic: '/ˈhʌndrəd/', definition: 'num. 百', example: 'A hundred people.' },
  thousand: { word: 'thousand', phonetic: '/ˈθaʊznd/', definition: 'num. 千', example: 'A thousand thanks.' },
  million: { word: 'million', phonetic: '/ˈmɪljən/', definition: 'num. 百万', example: 'A million dollars.' },
};

export function getLocalDictEntry(word: string): DictEntry | undefined {
  return DICT[word.toLowerCase().trim()];
}

export function hasLocalDictEntry(word: string): boolean {
  return word.toLowerCase().trim() in DICT;
}
